using Microsoft.VisualStudio.TestTools.UnitTesting;
using QuantityMeasurementApp.BusinessLayer.Services;
using QuantityMeasurementApp.ModelLayer.DTO;
using QuantityMeasurementApp.ModelLayer.Entities;
using QuantityMeasurementApp.ModelLayer.Models;
using QuantityMeasurementApp.ModelLayer.Enums;
using QuantityMeasurementApp.RepoLayer.Repositories;

namespace QuantityMeasurementApp.Tests
{
    /// <summary>
    /// UC15 - N-Tier Architecture Tests.
    /// Tests cover:
    /// - Entity layer construction and data storage
    /// - Service layer business logic isolation
    /// - Repository singleton pattern
    /// - Cache repository save and getall operations
    /// - Layer separation and independence
    /// - Data flow between layers
    /// - Dependency injection pattern
    /// - Backward compatibility with UC1-UC14
    /// - All measurement categories
    /// </summary>
    [TestClass]
    [DoNotParallelize]
    public class UC15_NTierArchitectureTest
    {
        private QuantityMeasurementCacheRepository _repository;
        private QuantityMeasurementServiceImpl _service;

        /// <summary>
        /// Runs before every test.
        /// Gets singleton cache repository and creates service with it.
        /// </summary>
        [TestInitialize]
        public void SetUp()
        {
            _repository = QuantityMeasurementCacheRepository.GetInstance();
            _service = new QuantityMeasurementServiceImpl(_repository);
        }

        // ─────────────────────────────────────────────────────────────────
        // Entity Layer Tests
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Entity should correctly store all fields passed in constructor.
        /// </summary>
        [TestMethod]
        public void Entity_Constructor_ShouldStoreAllFieldsCorrectly()
        {
            var entity = new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True");

            Assert.AreEqual("COMPARE", entity.Operation);
            Assert.AreEqual("1 FEET", entity.OperandOne);
            Assert.AreEqual("12 INCHES", entity.OperandTwo);
            Assert.AreEqual("True", entity.Result);
        }

        /// <summary>
        /// Entity Id should be automatically generated and not empty.
        /// </summary>
        [TestMethod]
        public void Entity_Id_ShouldBeAutoGenerated()
        {
            var entity = new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True");

            Assert.AreNotEqual(System.Guid.Empty, entity.Id);
        }

        /// <summary>
        /// Two entities created separately should have different Ids.
        /// </summary>
        [TestMethod]
        public void Entity_TwoInstances_ShouldHaveDifferentIds()
        {
            var entity1 = new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True");
            var entity2 = new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True");

            Assert.AreNotEqual(entity1.Id, entity2.Id);
        }

        /// <summary>
        /// Entity should store single operand operation like CONVERT correctly.
        /// </summary>
        [TestMethod]
        public void Entity_SingleOperandConstruction_ShouldStoreCorrectly()
        {
            var entity = new QuantityMeasurementEntity(
                "CONVERT", "1 FEET", "-", "12 INCHES");

            Assert.AreEqual("CONVERT", entity.Operation);
            Assert.AreEqual("1 FEET", entity.OperandOne);
            Assert.AreEqual("-", entity.OperandTwo);
            Assert.AreEqual("12 INCHES", entity.Result);
        }

        /// <summary>
        /// Entity should store binary operand operation like ADD correctly.
        /// </summary>
        [TestMethod]
        public void Entity_BinaryOperandConstruction_ShouldStoreCorrectly()
        {
            var entity = new QuantityMeasurementEntity(
                "ADD", "1 KILOGRAM", "1000 GRAM", "2 KILOGRAM");

            Assert.AreEqual("ADD", entity.Operation);
            Assert.AreEqual("1 KILOGRAM", entity.OperandOne);
            Assert.AreEqual("1000 GRAM", entity.OperandTwo);
            Assert.AreEqual("2 KILOGRAM", entity.Result);
        }

        /// <summary>
        /// Entity operation field should not be null after construction.
        /// </summary>
        [TestMethod]
        public void Entity_Operation_ShouldNotBeNull()
        {
            var entity = new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True");

            Assert.IsNotNull(entity.Operation);
        }

        /// <summary>
        /// Entity result field should not be null after construction.
        /// </summary>
        [TestMethod]
        public void Entity_Result_ShouldNotBeNull()
        {
            var entity = new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True");

            Assert.IsNotNull(entity.Result);
        }

        // ─────────────────────────────────────────────────────────────────
        // Repository Layer Tests
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Cache repository should return same instance every time.
        /// Verifies singleton pattern is correctly implemented.
        /// </summary>
        [TestMethod]
        public void CacheRepository_GetInstance_ShouldReturnSameInstance()
        {
            var instance1 = QuantityMeasurementCacheRepository.GetInstance();
            var instance2 = QuantityMeasurementCacheRepository.GetInstance();

            Assert.AreSame(instance1, instance2);
        }

        /// <summary>
        /// Cache repository Save should add entity to the list.
        /// </summary>
        [TestMethod]
        public void CacheRepository_Save_ShouldAddEntityToList()
        {
            int countBefore = _repository.GetAll().Count;

            _repository.Save(new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True"));

            int countAfter = _repository.GetAll().Count;

            Assert.AreEqual(countBefore + 1, countAfter);
        }

        /// <summary>
        /// Cache repository GetAll should return non null list.
        /// </summary>
        [TestMethod]
        public void CacheRepository_GetAll_ShouldReturnNonNullList()
        {
            var result = _repository.GetAll();

            Assert.IsNotNull(result);
        }

        /// <summary>
        /// Cache repository Save then GetAll should contain saved entity.
        /// </summary>
        [TestMethod]
        public void CacheRepository_SaveThenGetAll_ShouldContainSavedEntity()
        {
            int countBefore = _repository.GetAll().Count;

            _repository.Save(new QuantityMeasurementEntity(
                "ADD", "1 KG", "1000 GRAM", "2 KG"));

            var result = _repository.GetAll();

            Assert.AreEqual(countBefore + 1, result.Count);
            Assert.AreEqual("ADD", result[result.Count - 1].Operation);
        }

        /// <summary>
        /// Cache repository should be same object across two service instances.
        /// Verifies singleton pattern gives consistent data.
        /// </summary>
        [TestMethod]
        public void CacheRepository_SameInstance_ShouldGiveConsistentData()
        {
            var repo1 = QuantityMeasurementCacheRepository.GetInstance();
            var repo2 = QuantityMeasurementCacheRepository.GetInstance();

            int countBefore = repo1.GetAll().Count;
            repo1.Save(new QuantityMeasurementEntity(
                "COMPARE", "1 FEET", "12 INCHES", "True"));

            Assert.AreEqual(countBefore + 1, repo2.GetAll().Count);
        }

        // ─────────────────────────────────────────────────────────────────
        // Service Layer Tests - Compare
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Service compare 1 feet and 12 inches should return true.
        /// </summary>
        [TestMethod]
        public void Service_Compare_OneFeetAndTwelveInches_ShouldReturnTrue()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// Service compare different values should return false.
        /// </summary>
        [TestMethod]
        public void Service_Compare_DifferentValues_ShouldReturnFalse()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(2, LengthEnum.FEET));

            Assert.IsFalse(result);
        }

        /// <summary>
        /// Service compare 1 kg and 1000 grams should return true.
        /// </summary>
        [TestMethod]
        public void Service_Compare_OneKgAndThousandGrams_ShouldReturnTrue()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, WeightEnum.KILOGRAM),
                new QuantityDTO(1000, WeightEnum.GRAM));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// Service compare 1 litre and 1000 millilitres should return true.
        /// </summary>
        [TestMethod]
        public void Service_Compare_OneLitreAndThousandMillilitre_ShouldReturnTrue()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, VolumeEnum.LITRE),
                new QuantityDTO(1000, VolumeEnum.MILLILITRE));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// Service compare should save entity to repository after operation.
        /// </summary>
        [TestMethod]
        public void Service_Compare_ShouldSaveEntityToRepository()
        {
            int countBefore = _repository.GetAll().Count;

            _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES));

            Assert.AreEqual(countBefore + 1, _repository.GetAll().Count);
        }

        // ─────────────────────────────────────────────────────────────────
        // Service Layer Tests - Convert
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Service convert 1 feet to inches should return 12.
        /// </summary>
        [TestMethod]
        public void Service_Convert_OneFeetToInches_ShouldReturnTwelve()
        {
            var result = _service.Convert(
                new QuantityDTO(1, LengthEnum.FEET), LengthEnum.INCHES);

            Assert.AreEqual(12, result.Value, 0.001);
        }

        /// <summary>
        /// Service convert 1 kg to gram should return 1000.
        /// </summary>
        [TestMethod]
        public void Service_Convert_OneKilogramToGram_ShouldReturnThousand()
        {
            var result = _service.Convert(
                new QuantityDTO(1, WeightEnum.KILOGRAM), WeightEnum.GRAM);

            Assert.AreEqual(1000, result.Value, 0.001);
        }

        /// <summary>
        /// Service convert should save entity to repository after operation.
        /// </summary>
        [TestMethod]
        public void Service_Convert_ShouldSaveEntityToRepository()
        {
            int countBefore = _repository.GetAll().Count;

            _service.Convert(
                new QuantityDTO(1, LengthEnum.FEET), LengthEnum.INCHES);

            Assert.AreEqual(countBefore + 1, _repository.GetAll().Count);
        }

        // ─────────────────────────────────────────────────────────────────
        // Service Layer Tests - Add
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Service add 1 feet and 12 inches should return 2 feet.
        /// </summary>
        [TestMethod]
        public void Service_Add_OneFeetAndTwelveInches_ShouldReturnTwoFeet()
        {
            var result = _service.Add(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES),
                LengthEnum.FEET);

            Assert.AreEqual(2, result.Value, 0.001);
        }

        /// <summary>
        /// Service add 1 kg and 1000 grams should return 2 kg.
        /// </summary>
        [TestMethod]
        public void Service_Add_OneKgAndThousandGrams_ShouldReturnTwoKg()
        {
            var result = _service.Add(
                new QuantityDTO(1, WeightEnum.KILOGRAM),
                new QuantityDTO(1000, WeightEnum.GRAM),
                WeightEnum.KILOGRAM);

            Assert.AreEqual(2, result.Value, 0.001);
        }

        /// <summary>
        /// Service add should save entity to repository after operation.
        /// </summary>
        [TestMethod]
        public void Service_Add_ShouldSaveEntityToRepository()
        {
            int countBefore = _repository.GetAll().Count;

            _service.Add(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(1, LengthEnum.FEET),
                LengthEnum.FEET);

            Assert.AreEqual(countBefore + 1, _repository.GetAll().Count);
        }

        // ─────────────────────────────────────────────────────────────────
        // Service Layer Tests - Subtract
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Service subtract 1 feet from 2 feet should return 1 feet.
        /// </summary>
        [TestMethod]
        public void Service_Subtract_TwoFeetMinusOneFeet_ShouldReturnOneFeet()
        {
            var result = _service.Subtract(
                new QuantityDTO(2, LengthEnum.FEET),
                new QuantityDTO(1, LengthEnum.FEET));

            Assert.AreEqual(1, result.Value, 0.001);
        }

        /// <summary>
        /// Service subtract should save entity to repository after operation.
        /// </summary>
        [TestMethod]
        public void Service_Subtract_ShouldSaveEntityToRepository()
        {
            int countBefore = _repository.GetAll().Count;

            _service.Subtract(
                new QuantityDTO(2, LengthEnum.FEET),
                new QuantityDTO(1, LengthEnum.FEET));

            Assert.AreEqual(countBefore + 1, _repository.GetAll().Count);
        }

        // ─────────────────────────────────────────────────────────────────
        // Service Layer Tests - Divide
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Service divide 2 feet by 1 feet should return 2.
        /// </summary>
        [TestMethod]
        public void Service_Divide_TwoFeetByOneFeet_ShouldReturnTwo()
        {
            double result = _service.Divide(
                new QuantityDTO(2, LengthEnum.FEET),
                new QuantityDTO(1, LengthEnum.FEET));

            Assert.AreEqual(2, result, 0.001);
        }

        /// <summary>
        /// Service divide should save entity to repository after operation.
        /// </summary>
        [TestMethod]
        public void Service_Divide_ShouldSaveEntityToRepository()
        {
            int countBefore = _repository.GetAll().Count;

            _service.Divide(
                new QuantityDTO(2, LengthEnum.FEET),
                new QuantityDTO(1, LengthEnum.FEET));

            Assert.AreEqual(countBefore + 1, _repository.GetAll().Count);
        }

        // ─────────────────────────────────────────────────────────────────
        // Layer Separation Tests
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Service should work independently without controller.
        /// Verifies service layer isolation.
        /// </summary>
        [TestMethod]
        public void LayerSeparation_ServiceShouldWorkWithoutController()
        {
            var repo = QuantityMeasurementCacheRepository.GetInstance();
            var service = new QuantityMeasurementServiceImpl(repo);

            bool result = service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// Two services with same repository should share same data.
        /// Verifies singleton repository pattern.
        /// </summary>
        [TestMethod]
        public void LayerSeparation_TwoServicesWithSameRepo_ShouldShareData()
        {
            var repo = QuantityMeasurementCacheRepository.GetInstance();
            var service1 = new QuantityMeasurementServiceImpl(repo);
            var service2 = new QuantityMeasurementServiceImpl(repo);

            int countBefore = repo.GetAll().Count;

            service1.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES));

            Assert.AreEqual(countBefore + 1, repo.GetAll().Count);
        }

        // ─────────────────────────────────────────────────────────────────
        // Data Flow Tests
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// QuantityDTO should flow correctly through service and return result.
        /// </summary>
        [TestMethod]
        public void DataFlow_QuantityDTO_ShouldFlowCorrectlyThroughService()
        {
            var input = new QuantityDTO(1, LengthEnum.FEET);

            var result = _service.Convert(input, LengthEnum.INCHES);

            Assert.IsNotNull(result);
            Assert.AreEqual(12, result.Value, 0.001);
            Assert.AreEqual(LengthEnum.INCHES, result.Unit);
        }

        /// <summary>
        /// Service should return correct QuantityDTO after add operation.
        /// </summary>
        [TestMethod]
        public void DataFlow_ServiceShouldReturnCorrectDTOAfterAdd()
        {
            var result = _service.Add(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES),
                LengthEnum.FEET);

            Assert.IsNotNull(result);
            Assert.AreEqual(2, result.Value, 0.001);
            Assert.AreEqual(LengthEnum.FEET, result.Unit);
        }

        // ─────────────────────────────────────────────────────────────────
        // Backward Compatibility Tests UC1 to UC14
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// UC1 - Feet equality should still work after N-Tier refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC1_FeetEquality_ShouldWork()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(1, LengthEnum.FEET));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// UC3 - Feet to inches comparison should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC3_FeetToInchesComparison_ShouldWork()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// UC4 - Yard to feet comparison should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC4_YardToFeetComparison_ShouldWork()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, LengthEnum.YARDS),
                new QuantityDTO(3, LengthEnum.FEET));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// UC5 - Length conversion should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC5_LengthConversion_ShouldWork()
        {
            var result = _service.Convert(
                new QuantityDTO(1, LengthEnum.FEET), LengthEnum.INCHES);

            Assert.AreEqual(12, result.Value, 0.001);
        }

        /// <summary>
        /// UC6 - Length addition should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC6_LengthAddition_ShouldWork()
        {
            var result = _service.Add(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES),
                LengthEnum.FEET);

            Assert.AreEqual(2, result.Value, 0.001);
        }

        /// <summary>
        /// UC9 - Weight equality should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC9_WeightEquality_ShouldWork()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, WeightEnum.KILOGRAM),
                new QuantityDTO(1000, WeightEnum.GRAM));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// UC11 - Volume equality should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC11_VolumeEquality_ShouldWork()
        {
            bool result = _service.Compare(
                new QuantityDTO(1, VolumeEnum.LITRE),
                new QuantityDTO(1000, VolumeEnum.MILLILITRE));

            Assert.IsTrue(result);
        }

        /// <summary>
        /// UC12 - Subtraction should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC12_Subtraction_ShouldWork()
        {
            var result = _service.Subtract(
                new QuantityDTO(10, LengthEnum.FEET),
                new QuantityDTO(5, LengthEnum.FEET));

            Assert.AreEqual(5, result.Value, 0.001);
        }

        /// <summary>
        /// UC12 - Division should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC12_Division_ShouldWork()
        {
            double result = _service.Divide(
                new QuantityDTO(10, LengthEnum.FEET),
                new QuantityDTO(2, LengthEnum.FEET));

            Assert.AreEqual(5, result, 0.001);
        }

        /// <summary>
        /// UC14 - Temperature comparison should still work after refactoring.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC14_TemperatureComparison_ShouldWork()
        {
            var t1 = new Quantity<TemperatureEnum>(0, TemperatureEnum.CELSIUS);
            var t2 = new Quantity<TemperatureEnum>(32, TemperatureEnum.FAHRENHEIT);

            Assert.IsTrue(t1.Equals(t2));
        }

        /// <summary>
        /// UC14 - Temperature addition should throw NotSupportedException.
        /// </summary>
        [TestMethod]
        public void BackwardCompatibility_UC14_TemperatureAddition_ShouldThrow()
        {
            var t1 = new Quantity<TemperatureEnum>(100, TemperatureEnum.CELSIUS);
            var t2 = new Quantity<TemperatureEnum>(50, TemperatureEnum.CELSIUS);

            try
            {
                t1.Add(t2, TemperatureEnum.CELSIUS);
                Assert.Fail("Expected NotSupportedException was not thrown.");
            }
            catch (System.NotSupportedException)
            {
                Assert.IsTrue(true);
            }
        }

        // ─────────────────────────────────────────────────────────────────
        // All Measurement Categories Tests
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Service should correctly handle all four measurement categories.
        /// </summary>
        [TestMethod]
        public void Service_AllMeasurementCategories_ShouldWorkCorrectly()
        {
            Assert.IsTrue(_service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES)));

            Assert.IsTrue(_service.Compare(
                new QuantityDTO(1, WeightEnum.KILOGRAM),
                new QuantityDTO(1000, WeightEnum.GRAM)));

            Assert.IsTrue(_service.Compare(
                new QuantityDTO(1, VolumeEnum.LITRE),
                new QuantityDTO(1000, VolumeEnum.MILLILITRE)));

            var t1 = new Quantity<TemperatureEnum>(0, TemperatureEnum.CELSIUS);
            var t2 = new Quantity<TemperatureEnum>(32, TemperatureEnum.FAHRENHEIT);
            Assert.IsTrue(t1.Equals(t2));
        }

        /// <summary>
        /// Multiple operations should all be saved to repository.
        /// Verifies complete data flow across all layers.
        /// </summary>
        [TestMethod]
        public void Service_MultipleOperations_ShouldAllBeSavedToRepository()
        {
            int countBefore = _repository.GetAll().Count;

            _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET),
                new QuantityDTO(12, LengthEnum.INCHES));

            _service.Add(
                new QuantityDTO(1, WeightEnum.KILOGRAM),
                new QuantityDTO(1000, WeightEnum.GRAM),
                WeightEnum.KILOGRAM);

            _service.Convert(
                new QuantityDTO(1, VolumeEnum.LITRE),
                VolumeEnum.MILLILITRE);

            Assert.AreEqual(countBefore + 3, _repository.GetAll().Count);
        }
    }
}